<div>
  <?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
  <?php endif ?>
</div>

<a href="/users/new">New user</a>

<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
  <input type="submit" value="Search" />
</form>

<table>
  <?php foreach ($users as $user): ?>
    <tr>
      <td>
          <?= htmlspecialchars($user['id']) ?>
      </td>
      <td>
          <a href="/users/<?= $user['id'] ?>"><?= htmlspecialchars($user['name']) ?></a>
      </td>
    </tr>
  <?php endforeach ?>
</table>
